# Generated by Django 3.0.8 on 2020-07-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('crew', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=255)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_position', models.CharField(max_length=255)),
                ('employee_salary', models.CharField(max_length=255)),
                ('active_worker', models.BooleanField(default=True)),
                ('date_joined', models.DateField()),
                ('feedback', models.TextField()),
                ('employee_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Department')),
            ],
        ),
    ]
